import Head from "next/head";
import {
  Box,
  Button,
  Center,
  FlatList,
  Heading,
  HStack,
  Input,
  Text,
} from "native-base";
import { useState } from "react";

const checkIfPackageAvailableInData = (data: any, name: any) => {
  if (data) {
    for (let i = 0; i < data.length; i++) {
      if (data[i].package.name === name) {
        return false;
      }
    }
  }
  return true;
};

export default function Home(props) {
  const [packageName, setPackageName] = useState("");
  const [searchResults, setSearchResults] = useState(null);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center h="100vh">
        <Heading size="2xl">Does my package already exists?</Heading>

        <Text>Type your package name</Text>

        <form method="post">
          <HStack space="4">
            <Input
              onChangeText={(packageName: any) => {
                setPackageName(packageName);
              }}
            />
            <Button
              onPress={async () => {
                const data = await getPackage(packageName);
                setSearchResults(data);
              }}
            >
              submit
            </Button>
          </HStack>
        </form>
        <Text>
          {checkIfPackageAvailableInData(searchResults?.objects, packageName)
            ? "Not Found You are good to go"
            : "Sorry bruh"}
        </Text>
        <FlatList
          data={searchResults?.objects}
          renderItem={({ item }: any) => {
            return <Box h="60">{item?.package?.name}</Box>;
          }}
          keyExtractor={(item: any) => item?.package?.name}
        />
      </Center>
    </>
  );
}

async function getPackage(name) {
  const response = await fetch(
    "https://registry.npmjs.com/-/v1/search?text=" + name + "&size=20"
  );
  return response.json();
}
