import Head from "next/head";
import styles from "../styles/Home.module.css";
import bodyParser from "body-parser";
import util from "util";
import {Heading} from 'native-base';
const getBody = util.promisify(bodyParser.urlencoded());

const checkIfPackageAvailableInData = (data, name) => {
  if (data) {
    for (let i = 0; i < data.length; i++) {
      if (data[i].package.name === name) {
        return false;
      }
    }
  }
  return true;
};

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading size="2xl">
          Welcome to Does my package already exists?
        </Heading>

        <p className={styles.description}>Type your package name</p>

        <form method="post">
          <input name="name" />
          <button type="submit">submit</button>
        </form>
        <p>
          {checkIfPackageAvailableInData(props.data?.objects, props.name)
            ? "Not Found You are good to go"
            : "Sorry bruh"}
        </p>
      </main>
    </div>
  );
}

async function getPackage(name) {
  const response = await fetch(
    "https://registry.npmjs.com/-/v1/search?text=" + name + "&size=20"
  );
  return response.json();
}
export async function getServerSideProps({ req, res }) {
  if (req.method === "POST") {
    await getBody(req, res);
  }
  const name = req.body?.name ?? "";
  const data = await getPackage(name);
  return {
    props: {
      name: name,
      data: data.objects.length !== 0 ? data : "404",
    },
  };
}